### ISSUE TITLE
Error and mod not functional.

### ISSUE THREAD

**Issue by xy172** [MaLiN2223/WaypointTogetherContinued#4]
Mod is erroring and then nonfunctional. This in on a single player server opened to lan if that makes a difference.

12.12.2024 12:06:35 [Error] [waypointtogethercontiued] An exception was thrown when trying to load assembly:
12.12.2024 12:06:35 [Error] [waypointtogethercontiued] Exception: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Vintagestory.Common.ModContainer.LoadAssembly(ModCompilationContext compilationContext, ModAssemblyLoader loader) in VintagestoryLib\Common\API\ModContainer.cs:line 481

[server-main.log](https://github.com/user-attachments/files/18115771/server-main.log)

**Comment by MaLiN2223** [comment]
Which version is that for?
Can you try removing the mod manually and adding it again?
